# Try catch
try
  a = 1
catch hi
  console.log hi
