let a;

try {
  a = 1;
} catch (hi) {
  console.log(hi);
}

try {
  let b = 1;
} catch (e$) {}