let a;

try {
  a = 1;
} catch (hi) {
  console.log(hi);
}